package com.fiskra.sample.vaadin.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AppMenuDesign extends HorizontalLayout {
    protected CssLayout menu;
    protected Button dashboard;
    protected Button dashboard2;
    protected Button admin;
    protected CssLayout content;

    public AppMenuDesign() {
        Design.read(this);
    }
}
